### ISSUE TITLE
cache.* 404s on permalinks

### ISSUE THREAD

**Issue by dbwpe** [wpengine/hgv#53] opened 2015-01-17 20:35 UTC
When visiting cache.(php|hhvm).hgv.dev/totallyrealpage/ with permalinks on, I get a 404.

Replication:

1. `vagrant up`
2. Log in to wp-admin, and change permalinks to anything other than Default.
3. Try to visit http://cache.php.hgv.dev/hello-world/ (default built-in WP post)
or http://cache.hhvm.hgv.dev/hello-world/ if you're testing there.
4. Try any other pages that use permalinks.

I haven't found anything useful in the logs, just 404s in nginx access and varnishncsa.log

It looks like it's interpreting the path as a literal directory.

**Comment by zamoose** [comment] 2015-01-19 05:13
@dbwpe Is it all permalinks or simply a subset? I'm assuming this behavior doesn't occur with the out-of-the-box query string setup, right?

**Comment by zamoose** [comment] 2015-01-20 03:39
I can confirm this as legitimate. I am able to reproduce it.

**Comment by zamoose** [comment] 2015-01-20 21:34
Just documenting here, to try to rubber duck this a bit AND allow folks to potentially understand flow better:

Requests to `cache.[your domain]` are handled thus:

1. Nginx on port 80 on the front end handles the initial request (via the VHost defined in [wpcache.conf](/wpengine/hgv/provisioning/roles/wordpress/templates/etc/nginx/wpcache.conf))
2. Nginx hands off to Varnish on port 6081.
3. Varnish checks whether it's a) supposed to be caching a page b) whether it has the page.
4. If Varnish doesn't have the page, it then pushes the request back to Nginx on port 8083 (via [upstream.conf](/wpengine/hgv/provisioning/roles/nginx/templates/etc/nginx/conf.d/upstream.conf)). (I know it sounds weird to go Nginx->Varnish->Nginx->FPM/HHVM, but this is because Varnish [does not currently support hand-offs to FastCGI](https://www.varnish-cache.org/trac/wiki/Future_Feature#FCGIbackendsupport)).
5. Nginx ferries the request over to the back-end (FPM or HHVM).
6. WordPress sets the constants based on perceived `HTTP_HOST`:

    ```php
    define('WP_SITEURL', 'http://cache.php.hgv.dev');
    define('WP_HOME', 'http://cache.php.hgv.dev');
    define('WP_CACHE_KEY_SALT', 'cache_wpe_php_1');
    ```
7. Back-end hands the result back to Nginx.
8. Nginx hands it back to Varnish.
9. Varnish, last of all, sends the result back to the requester.

Taking a stroll through the logs, it *appears* as though the requests are making it through correctly. 

Odd side-effect: All of my PHP-based cache.* URLs are just white-screening, while HHVM at least hast the courtesy to display an Nginx Not Found error.

**Comment by zamoose** [comment] 2015-01-20 21:41
One odd thing to note:
The cached PHP version seems to be trying to hand off to Nginx on :8083 directly when attemptingto access `/wp-admin/` instead of going through the Varnish intermediary. HHVM does not.

Anyone else seeing that?

**Comment by markkelnar** [comment] 2015-02-11 15:04
Closing this issue because I believe it's resolved now. @dbwpe, if you still experience this after the latest changes, please reopen the issue.

**Closed by markkelnar** 2015-02-11 15:04 UTC
Labels: bug, priority-medium

**Comment by scriptmaster** [comment] 2017-11-21 14:45
Had a similar issue and I added this in my nginx conf to make it work for wordpress /index.php/permalink urls in nginx hhvm 3.21

Adding this for everyone's reference:

1. Improved:

```
location / {
...
fastcgi_param  SCRIPT_FILENAME $document_root/index.php$fastcgi_script_name;
...
}
```

or 

2. Alternative (less elegant):

```
location / {
...
rewrite ^/([^\.]+)$ /index.php/$1 break;
...
}

```
