### ISSUE TITLE
Failure on global-status --prune

### ISSUE THREAD

**Issue by Ipstenu** [wpengine/hgv#204] opened 2015-08-07 23:55 UTC
I found this because I like to use Vagrant Manager (https://github.com/lanayotech/vagrant-manager/issues/106 just in case you were wondering)

$ vagrant global-status --prune
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /Users/mika/Sites/HGV/Vagrantfile
Line number: 299
Message: Errno::ENOENT: No such file or directory - ./provisioning/default-install.yml

I deleted HGV and reinstalled and I get the same thing :( Manually provisioning works but it still shows that error on prune.

**Comment by zamoose** [comment] 2015-08-08 01:19
Looks like the `global` command doesn't know how to find the `cwd`, at least if I'm reading it right. 

Probably need to specify an absolute path to the YAML file. I'll take a look.

**Comment by ericmann** [comment] 2015-08-10 21:07
I just tested this and could only reproduce on an older checkout I had - when my HGV build is on `master`I can no longer reproduce. Can you easily tell what hash your clone is at?

**Comment by Ipstenu** [comment] 2015-08-11 17:21
As mentioned, I did a clean checkout (assuming that mine was borked - deleted everything and reinstalled) and had the exact same issue. But I just did it again.

`git clone --recursive https://github.com/wpengine/hgv.git` and CD to `hgv` and then I run `vagrant up`

Hash is f97aaa8e1e819cedafc313e176d3d52423fdd4ba

**Comment by ericmann** [comment] 2015-08-13 22:42
I've spent some more time trying to track this down and I'm at a loss. The first confusing part is the error message referencing line 299 of the Vagrantfile - it's only 88 lines long :(

I'm thinking there might be a conflict deeper in vagrant-manager, so I'll give that a try and see what happens.

**Comment by ericmann** [comment] 2015-08-14 16:04
@Ipstenu after spending some time with Vagrant Manager, I'm convinced it's a deeper conflict within that application. Without it installed, everything runs just fine (even `vagrant global-status --prune`). However, it tries to do something internally to get the global status and, if _any_ error occurs, alerts you that it's an issue with the `global-status` command.

I'm not convinced that it is, but I'm also not sure what's triggering the conflict and will have to dig deeper to figure things out. For now, though, I wanted to give at least this much of an update before I tag the ticket as lower priority. It's still something that can be fixed, but will have to wait a bit.

**Comment by Ipstenu** [comment] 2015-08-14 16:08
Thank you for keeping me updated! It's a bummer for me (I'm so incredibly lazy) but I totally understand.

**Comment by andrew40** [comment] 2015-08-30 19:47
The owner of Vagrant Manager is aware of the problem and has suggested users revert to version 2.4.1 in the meantime. I have reverted back and the issues have all gone. I believe he has shelved the use of vagrant global-status --prune and reverting back to the more power hungry vagrant status.

More here .. https://github.com/lanayotech/vagrant-manager/issues/111

**Comment by ericmann** [comment] 2015-09-23 20:38
Closing as this is a known issue in Vagrant Manager itself.

**Closed by ericmann** 2015-09-23 20:38 UTC
Labels: bug, priority-low, Vagrant
