### ISSUE TITLE
HHVM MySQL Connection Issues

### ISSUE THREAD

**Issue by futuernorn** [wpengine/hgv#100] opened 2015-03-11 16:05 UTC
On fresh installs, I am receiving a "Error establishing a database connection" error at the HHVM WordPress install, http://hhvm.hgv.dev/, while http://php.hgv.dev/ is able to load without issue. The HHVM error log shows:
> vagrant@hgv:~$ tail -2 /var/log/hhvm/error.log
> [Wed Mar 11 15:02:08 2015] [hphp] [1471:7fb6f37ff700:1:000001] [] \nWarning: mysql_connect(): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
> [Wed Mar 11 15:02:08 2015] [hphp] [1471:7fb6f37ff700:1:000002] [] \nWarning: mysql_connect(): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) in /hgv_data/sites/hhvm/wp-includes/wp-db.php on line 1416

This particular issue appeared with fresh vagrant instances on both OSX 10.10 and Lubuntu 14.10.

Initial `vagrant up` provisioning preceding this issue is shared [here](https://gist.github.com/futuernorn/2342e4fff222a8d67c50) (though there was no clear indication of a related error in this process).

---
For a couple quick fixes, updating local-config.php for the hhvm install appears to be one way to resolve the issue (localhost -> 127.0.0.1):
```php
define('DB_HOST', '127.0.0.1');
```
The above is obviously less than ideal. Alternatively, adding a link allowed the hhvm site to connect, e.g.:
```
ln -s /var/run/mysqld/mysqld.sock /tmp/mysql.sock
```

---
For a better option, I saw the following from the HHVM [documentation](http://docs.hhvm.com/manual/en/function.mysql-connect.php):
> Note:
> Whenever you specify "localhost" or "localhost:port" as server, the MySQL client library will override this and try to connect to a local socket (named pipe on Windows). If you want to use TCP/IP, use "127.0.0.1" instead of "localhost". If the MySQL client library tries to connect to the wrong local socket, you should set the correct path as in your PHP configuration and leave the server field blank.

So the more robust solution appears to be to update the /etc/hhvm/php.ini file with the following line:
```
pdo_mysql.default_socket = /var/run/mysqld/mysqld.sock
```
[referenced from: http://docs.hhvm.com/manual/en/ref.pdo-mysql.php]

However that particular module didn't appear to be the one at-hand for this issue. Instead the hhvm.mysql.socket	setting (found via a 'hhvminfo.php' page copied from this other issue https://github.com/wpengine/hgv/issues/9) got everything running correctly:
> vagrant@hgv:~$ grep socket /etc/hhvm/php.ini
> hhvm.mysql.socket = /var/run/mysqld/mysqld.sock
> vagrant@hgv:~$ sudo service hhvm restart
> * Restarting HHVM FastCGI Daemon hhvm

**Comment by zamoose** [comment] 2015-03-11 17:16
Great find! I'll see if I can replicate it at all.

Kind of wondering why no one else has stumbled across this one.

**Comment by purpleorangegames** [comment] 2015-03-17 12:35
Just to add a note, I had this exactly issue yesterday after updating hhvm on my ubuntu server.
I already had two wordpress installs running and one of them printed "Error establishing a database connection" and the other would show an incomplete page. None of them was able to enter in wp-admin.

I fixed the issue with the command from above:
ln -s /var/run/mysqld/mysqld.sock /tmp/mysql.sock

**Comment by markkelnar** [comment] 2015-03-17 16:58
Confirmed, I am experiencing this too on latest HHVM and new HGV vagrant.  I'll do some investigation also.

**Comment by markkelnar** [comment] 2015-03-17 17:08
Looks like it's been identified and targeting a fix for HHVM 3.6.1
https://github.com/facebook/hhvm/issues/4987

But what should be do in the mean time?  Set up the symlink?  apt install 3.3.5 ?

**Comment by zamoose** [comment] 2015-03-17 17:13
It's got to be the symlink until upstream fixes, I'd say. The other options really aren't, as reverting to older HHVM will likely entail messing with a host of other ini settings.

My vote is a documented symlink with a back-out reminder for when the patched HHVM ships. There's no harm in having the symlink anyways, IMHO, even if we forget about it later. Inelegant, yes, but not a huge issue. 

--
Doug Stewart

**Comment by markkelnar** [comment] 2015-03-17 17:15
Sounds good.  I can code a fix and test it.

**Comment by markkelnar** [comment] 2015-03-17 17:39
The symlink doesn't survive a 'vagrant reload' because it's in /tmp.  Going to test specifying the socket in the hhvm ini file.

**Comment by markkelnar** [comment] 2015-03-17 20:38
The PR has been merged, someone else want to confirm that this fixes this issue?

**Comment by GeorgeVasil** [comment] 2015-03-20 10:11
adding 

hhvm.mysql.socket = /var/run/mysqld/mysqld.sock

to 

/etc/hhvm/php.ini 

solved the issue for me.

**Comment by zamoose** [comment] 2015-03-20 18:03
Great! Closing this one out.

**Closed by zamoose** 2015-03-20 18:03 UTC
Labels: bug, HHVM, Percona
