### ISSUE TITLE
Failed task - major issue?

### ISSUE THREAD

**Issue by stevengeorgeharris** [wpengine/hgv#287] opened 2016-01-19 17:33 UTC
I'm running Vagrant Up and coming across the error below. 

If I visit http://hhvm.hgv.test it just takes me to the same root as http://hgv.test/ are these related?

`fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "ERROR! 'backend' is undefined"}`

**Comment by royhuggins** [comment] 2016-01-19 22:51
I am having the exact same issue. OS X 10.10.4 with VirtualBox. I also get the same root as hgv.test when I go to hhvm.hgv.test.

I have run HGV before on this same machine without this issue. It seems to have been introduced by a recent update. However, I don't know exactly what the provisioner is doing at this point in the process so I don't understand the error. 

`==> hgv: TASK [wordpress : Enable PML viewing for {{ enviro }} {{ backend }}] ***********
==> hgv: fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "ERROR! 'backend' is undefined"}`

**Comment by royhuggins** [comment] 2016-01-19 23:03
If after the failed provisioning, I run `vagrant halt` then `vagrant up`, it is only hhvm.hgv.test and php.hgv.test that fail. Chrome reports ERR_INVALID_RESPONSE. Everything in admin.hgv.test functions as expected.

**Comment by dietcheese** [comment] 2016-01-19 23:39
Same problem here.  Running Ubuntu 15.10, latest Vagrant/Virtualbox/HGV.

**Comment by stevengeorgeharris** [comment] 2016-01-20 12:01
I believe a package has been updated somewhere but as @royhuggins says, I can't figure out what that task does. 

I'd say this is a major bug as it's destroyed my working environment completely.

**Comment by royhuggins** [comment] 2016-01-20 17:41
Yep. Last commit to the hgv repo was Sep 30, so it looks like the problem is introduced by someone else's package update.

**Comment by chrisleach** [comment] 2016-01-21 13:56
Same issue here. Same setup as you guys, same error. Any custom sites I set up just show the contents of the dashboard folder. (the docs site)

**Comment by stevengeorgeharris** [comment] 2016-01-21 15:14
I'm just using a lightweight alternative for the moment - it's easy to install/set-up everything that HGV has.

**Comment by boogah** [comment] 2016-01-21 18:40
I've manually fixed on my install this by changing adding these lines:

```
    cache.php.hgv.test    php;
    php.hgv.test    php;
    cache.hhvm.hgv.test    hhvm;
    hhvm.hgv.test    hhvm;
```

Right under:

```
    ## Upstream for hhvm ## After this line, domains are inserted by the provisioning scripts. Do Not Edit.
```

In `/etc/nginx/conf.d/www-hhvm.conf`. You'll need to `sudo` to have proper permissions on that file!

Once those lines are added back in, you need to kick nginx. You can do that with this command:

```
sudo service nginx restart
```

Hope this helps!

**Comment by boogah** [comment] 2016-01-21 20:18
@stevengeorgeharris I'm interested to hear about the other environment you're using! Feel free to DM me on Twitter or send me an email (github_user@gmail.com) with a link.

**Comment by jb510** [comment] 2016-01-21 20:35
Woot!  @boogah that fixed it for me too.  

I've been trying to figure this out for 2 weeks...  that's when I noticed it broke, but it could have been 2-4 weeks ago...

**Comment by jb510** [comment] 2016-01-21 21:06
I just combing through code I don't fully understand, but I feel like there should be {{ vars }} here for ansible to fill in, no?

https://github.com/wpengine/hgv/blame/357210dee28321fb1e1baa37dfcfa4fb8fb56080/provisioning/roles/wordpress/templates/etc/nginx/conf.d/wordpress.conf#L6

**Comment by royhuggins** [comment] 2016-01-21 21:19
That did it for me, too, @boogah. Thanks much!

For those who are hazy on how hgv is structured:

Once you finish provisioning and get the error we've all complained about, do `vagrant ssh` and then follow @boogah's instructions. 

Also obvious but perhaps worth saying: any time you provision you'll need to do this process again.

**Comment by jb510** [comment] 2016-01-21 23:21
I've got a working patch coming

**Comment by markkelnar** [comment] 2016-02-01 19:29
Yes, the error reported by @royhuggins prevents the rest of the provisioning to run, which creates the correct configurations and domains for Nginx under /etc/nginx/conf.d.  I'm going to unwrap that a little and try to diagnose the root cause.

**Comment by markkelnar** [comment] 2016-02-01 19:48
@stevengeorgeharris @royhuggins @boogah #293  should fix the original issue.

**Comment by boogah** [comment] 2016-02-01 21:57
I've tested #293 by provisioning a new Vagrant. It fixes the problems I was seeing on my install.

Thanks for the fix @markkelnar!

**Closed** 2016-02-01 21:59 UTC
